Important notes
Aam-Digital/ndb-core pull request #1297
Opened 2022-05-28 21:07 UTC by Schottkyc137

see issue: #1238

### Visible/Frontend Changes
- [x] Add a dashboard widget that shows important notes
- [] Make the notes configurable to a user

2022-07-04 12:33 UTC, TheSlimvReal requested changes

2022-07-04 12:33 UTC, TheSlimvReal commented on src/app/child-dev-project/notes/dashboard-widgets/important-notes/important-notes.component.html
> +          (click)="openNote(row)"
Mouse should indicate that row is clickable (changing the cursor style)

2022-07-05 14:06 UTC, sleidig reviewed
Only review UI so far: I like how this looks and works overall :smiley: 

Are the notes sorted by anything? Maybe by date makes sense?
Possibly could also indicate somehow whether it's "Urgent" or only "Needs Followup"

2022-08-17 13:52 UTC, Schottkyc137 commented
All issues should be fixed now. I have also re-introduced the color as background since different notes can have a different color (red or orange)

2022-08-23 09:28 UTC, TheSlimvReal requested changes
Looks solid now @sleidig can you give a last UX review? I am still struggling a little with the very strong red color on all the warning notes.

2022-08-25 10:13 UTC, sleidig commented
Very much like the widget overall. I do agree about the color being a bit overwhelming though. How about using the less heavy styling we have on the "record attendance" view, something like this:
![image](https://user-images.githubusercontent.com/1682541/186638306-0bcb4f74-f7cd-4fe3-af5e-e40f870dcb0c.png)
(for reference, this is `.row-view { border-left: 8px solid orange; }`)

@TheSlimvReal I think you did the technical code review? I didn't look closer at that yet.

2022-08-30 16:25 UTC, Schottkyc137 commented
> Very much like the widget overall. I do agree about the color being a bit overwhelming though. How about using the less heavy styling we have on the "record attendance" view, something like this: ![image](https://user-images.githubusercontent.com/1682541/186638306-0bcb4f74-f7cd-4fe3-af5e-e40f870dcb0c.png) (for reference, this is `.row-view { border-left: 8px solid orange; }`. Doesn't look perfectly clean yet without spacing, maybe we should try with an extra, empty but colored td instead)
> 
> @TheSlimvReal I think you did the technical code review? I didn't look closer at that yet.

I very much like the idea of having a more subtle hint instead of changing the whole background color. What do you think about the following?
<img width="374" alt="Bildschirmfoto 2022-08-30 um 18 22 26" src="https://user-images.githubusercontent.com/45085299/187489464-b3798f5c-633d-443a-8add-2538ddd42e6a.png">

Though this is not more than a potential alternative; I don't have any strong opinions on either design.

2022-09-20 14:01 UTC, TheSlimvReal approved these changes
Nice work, I like where we got with this and I think a lot of organisations can use this

2022-09-20 14:03 UTC, merged