Add first and last buttons
Aam-Digital/ndb-core pull request #1304
Opened 2022-05-31 17:33 UTC by Schottkyc137

see issue: #1303

### Visible/Frontend Changes
- [x] Allow users to skip to the last or first participant

2022-06-16 11:47 UTC, TheSlimvReal requested changes
![image](https://user-images.githubusercontent.com/33730997/174063099-9203d43a-59a0-49a6-a1a4-f06c8d298a25.png)

The styling on mobile devices is a little broken now

2022-06-16 11:47 UTC, TheSlimvReal commented on src/app/child-dev-project/attendance/add-day-attendance/roll-call/roll-call.component.ts
> +    // because there is one more page than there are children
Lets make this comment a little less confusion and say that we just finalize the roll call instead of jumping to the last participant.

2022-06-30 20:30 UTC, sleidig approved these changes

2022-07-04 13:19 UTC, TheSlimvReal approved these changes
Looks nice now, thanks for adding this!

2022-07-04 13:21 UTC, merged