File upload fixes
Aam-Digital/ndb-core pull request #1562
Opened 2022-11-30 09:53 UTC by TheSlimvReal

The file upload has been restructured to be more in-line with other form components and to support the automatic form-update functionality.

### Visible/Frontend Changes
- [x] Uploading/removing files only happens when 'save' is clicked
- [x] No more confirmation popup when replacing/deleting files, as this can be undone by clicking 'cancel'

### Architectural/Backend Changes
- [x] `PUT`-Requests to CouchDB are executed in sequence in order to support uploading of multiple files at the same time
- [x] `EntityFormComponent` has been cleaned up to less often create new forms. Now it only creates the form one and then updates the values when needed.

2022-11-30 13:41 UTC, TheSlimvReal commented
Has been deployed to https://fu.aam-digital.com

2022-12-01 09:00 UTC, sleidig requested changes
really, really clean code and tests. :heart_eyes: 

Functional testing:
- [x] add file + cancel form--> file name still shows in field until reload
- [x] whenever saving something other then file fields, the "apply remote changes" popup shows up now

2022-12-01 11:50 UTC, TheSlimvReal commented on src/app/features/file/edit-file/edit-file.component.spec.ts
> +    expect(component.formControl).toHaveValue(null);
Got point, I now changed it all to `null` as this will get evicted when saving with the entity mapper

2022-12-01 11:51 UTC, TheSlimvReal commented
@sleidig sorry, I forgot to update the deployment after merging the master. The issues you mentioned seem to have been fixed after merging the latest changes from the master. I couldn't reproduce them afterwards.

2022-12-02 16:59 UTC, sleidig approved these changes

2022-12-02 17:02 UTC, merged