[WIP] user-editable dropdowns
Aam-Digital/ndb-core pull request #1661
Opened 2023-01-12 11:55 UTC by sleidig

see issue: #1642

2023-01-17 12:16 UTC, TheSlimvReal requested changes

2023-01-17 12:16 UTC, TheSlimvReal commented on src/app/core/configurable-enum/enum-dropdown/enum-dropdown.component.ts
> +  selector: "app-enum-dropdown",
Is there a reason for making this a extra component (and not just move the code to the `EditConfigurableEnumComponent`

2023-01-17 12:16 UTC, TheSlimvReal commented on src/app/core/entity-components/entity-utils/dynamic-form-components/edit-number/edit-number.stories.ts
> +console.log("X");
```suggestion
```

2023-01-17 12:59 UTC, TheSlimvReal commented on src/app/core/configurable-enum/basic-autocomplete/basic-autocomplete.component.html
> +  <fa-icon
Ok that would look bad 😅

2023-01-24 13:21 UTC, sleidig reviewed
Nice work!

The delay until "Add option xxx" is shown is confusing me - why did you decide against showing that in real-time?

I tuned the popup UI a bit to make it more consistent with other views. I would also like the option to cancel an edit - probably best to use reactiveForms then? (UI is there now but the logic is not because we use two-way binding currently)

2023-01-24 15:08 UTC, TheSlimvReal commented on src/app/core/configurable-enum/configurable-enum.service.ts
> +      id.replace(CONFIGURABLE_ENUM_CONFIG_PREFIX, "")
We are using pascal case for the entity types but the config prefix is lower case. This could of course be transformed.

2023-01-25 09:49 UTC, sleidig commented on src/app/core/config/config.service.ts
> +      await this.saveAllEnumsToDB(config);
-> if enum entities do not exist yet, try to save
-> try to save updated config after deleting enums (if permissions allow)

2023-01-25 09:59 UTC, sleidig commented on src/app/core/configurable-enum/configurable-enum.service.ts
> +      id.replace(CONFIGURABLE_ENUM_CONFIG_PREFIX, "")
--> config usually was writting without enum: prefix; we'll risk removing this safeguard here

2023-01-25 10:18 UTC, sleidig commented on src/app/core/configurable-enum/edit-enum-popup/edit-enum-popup.component.ts
> +      $localize`Are you sure that you want to delete the option ${value.label}?`
--> show feedback to user
--> delete option on confirmation
--> adapt reporting to handle "invalid option" (equality check to be changed)

2023-01-25 10:38 UTC, sleidig commented
- close button (no reset) in popup
- clear text on focus out if nothing was selected
- confirmation dialog for creating new option

2023-01-31 10:50 UTC, sleidig commented
To make initial config easier: If no ConfigurableEnum entity exists, create an empty one. (That way we can just define that a property is configurable-enum and leave creating of options to users also)

2023-02-01 17:30 UTC, sleidig commented
I think we wanted to reset the value to the actual selection when leaving focus. Currently I still see the string typed remaining in the field after clicking somewhere else, even when I didn't create it as a new option.

2023-02-03 12:14 UTC, sleidig reviewed
Code looks pretty good now! :-) 

- I could/did not test migration but already migrated instances seem stable now.
- One error on saving with newly created option:
  - create a new option
  - --> the new value is correctly displayed in the field 
  - save the entity form
  - go back to list and re-open that entity's details
  - --> the value is not set
  - (re-selecting it now and saving seems to work)

2023-02-06 06:08 UTC, TheSlimvReal commented on src/app/child-dev-project/attendance/dashboard-widgets/attendance-week-dashboard/attendance-week-dashboard.component.ts
> +    this.tableDataSource.data = groups
Its related in the way that they are now all able to properly group enums (also with the invalid option)

2023-02-07 08:23 UTC, sleidig reviewed
I still see the functional issue described before:

- create a new option
- --> the new value is correctly displayed in the field
- save the entity form
- go back to list and re-open that entity's details
- --> the value is not set
- (re-selecting it now and saving seems to work)

2023-02-07 08:23 UTC, sleidig commented on src/app/core/config/config-fix.ts
> +              "test"
test should probably not end up back in master?

2023-02-07 13:26 UTC, sleidig reviewed
Great :+1:  good to go now, I think. (I can't approve the PR here as I am the original author ...)

2023-02-07 16:05 UTC, TheSlimvReal approved these changes

2023-02-07 16:06 UTC, merged