Select current date when this is wanted in the property schema
Aam-Digital/ndb-core pull request #1796
Opened 2023-03-23 19:18 UTC by Schottkyc137

see issue: #1672 

### Architectural/Backend Changes
- [x] Current date is automatically selected when the property `startWithNow` is set to `true` in the `additional` section in a property schema of an entity

2023-03-28 14:54 UTC, sleidig reviewed
in some sense, this overlaps with the EntitySchemaField "defaultValue" (which, I think, we never use):
https://github.com/Aam-Digital/ndb-core/blob/0dae11599f79f85418e71ea449a90dfbc7411c09/src/app/core/entity/schema/entity-schema-field.ts#L48-L52

Might make sense to bring those two aspects together?

2023-04-18 14:06 UTC, sleidig commented on src/app/core/database/pouch-database.ts
> +              since: "$now",
```suggestion
              since: "now",
```

2023-04-18 15:31 UTC, TheSlimvReal requested changes
There are some problems with the `defaultValue` assignment in the `EntitySchemaService`. We somehow need to distinguish whether the actual value should be assigned or not. 
Generally, it would be nice if we could overwrite the constructor in a way that the default values are automatically assigned instead of having to take care of this in the edit components every time.

2023-04-18 15:31 UTC, sleidig reviewed
as I stumbled into a few issues when fixing the tests, a different possible approach just came to my mind:
What if we move defaultValue initialization to the Entity constructor, away from the EntityService/SchemaService loading. Otherwise we have to handle the special placeholders also in the transformToEntityFormat to avoid errors ...

2023-06-28 10:19 UTC, TheSlimvReal commented
I made some changes and think this is ready for a final review:

- default values are assigned centrally in the form service (and only persisted once this form is saved)
- changes in edit components were reverted
- default values are also assigned if the entity is **not** new (based on recent requirements)
- added the default value to further schemas where appropriate

@sleidig any further thoughts?

2023-06-30 09:28 UTC, sleidig requested changes
User Stories / Test cases:
- [x] new entity -> form shows default
- [x] existing entity with field defined -> form keeps existing value
- [x] existing entity with field undefined -> form keeps undefined value 
- [x] form shows default -> user deletes value -> entity gets saved with empty/undefined property (if not marked required)

:question: Is this the expected behavior? what happens with existing entities that have an empty field is maybe debatable. But I think setting defaults on existing entities creates some rather unexpected, slightly unpredictable user experience.

Once we are clear: Let's add these as additional unit tests also.

EDIT: behavior adapted now and all passed.

2023-06-30 09:28 UTC, sleidig commented on src/app/child-dev-project/notes/model/note.ts
> +    defaultValue: PLACEHOLDERS.CURRENT_USER,
would this need special handling to generically work for any innerDataType within an array?

2023-06-30 09:28 UTC, sleidig commented on src/app/core/entity/schema/entity-schema-field.ts
>     * (which is then run through dataType transformation);
```suggestion
   * Default values are applied to form fields before they are displayed to users
```

2023-07-04 10:06 UTC, merged