Visual regression testing
Aam-Digital/ndb-core pull request #1873
Opened 2023-05-04 20:37 UTC by sleidig

see issue: #1866 

trying a setup of percy to do visual regression tests

2023-05-08 11:15 UTC, TheSlimvReal commented on .github/workflows/pull-request-update.yml
> +      - run: npm install --save-dev @percy/cli
```suggestion
      - run: npm install
```
Percy is already a dev dependency and you probably also need all the other dependencies in order to run the app

2023-06-05 16:35 UTC, sleidig commented
@TheSlimvReal any good idea on speeding up the new pipeline so that it won't time out? Running locally I did manage the send [screenshots to Percy](https://percy.io/f45c2ede/aam-digital/builds/27321238/changed/1520200295?browser=edge&browser_ids=36%2C38%2C39%2C40&subcategories=unreviewed%2Cchanges_requested&viewLayout=side-by-side&viewMode=new&width=1280&widths=375%2C1280) (looks kinda cool and useful :sunglasses: ).

2023-06-09 10:04 UTC, TheSlimvReal requested changes
Not sure what affected the other tests to fail

2023-06-09 10:19 UTC, TheSlimvReal approved these changes

2023-06-21 15:56 UTC, merged