Configurable styles
Aam-Digital/ndb-core pull request #1953
Opened 2023-08-01 15:54 UTC by TheSlimvReal

see issue: #1949 

Generally it is possible to use CSS variables to change the theme colors as well as the font family/style etc.

### Colors
Here we have to assign a variable to each [hue](https://material.angular.io/guide/theming#palettes) which is a bit cumbersome and also raises the question, how these values are generated (probably a user would just want to choose one color and all others should be derived from it).
To pick the colors according to an [Material Design Color Palette](https://m2.material.io/design/color/the-color-system.html#tools-for-picking-colors) is also not super straight forward. 
There is no official API but some reverse engineered solutions ([thread](https://stackoverflow.com/questions/32942503/material-design-color-palette), [solution 1 (npm package)](https://www.npmjs.com/package/material-palette), [solution 2 (newer npm package)](https://www.npmjs.com/package/@aytek/material-color-picker?activeTab=readme), [solution 3 (code snippet)](https://github.com/mbitson/mcg/blob/master/scripts/controllers/ColorGeneratorCtrl.js#L163)).
Alternatively, we could refer to a tool like [this](https://materialpalettes.com/) and allow user to copy paste the result from it.

### Fonts
Changing the font works just like changing the colors but is much easier as we only need one variable for the font family.
The problem is where do we get the fonts from (dynamically)?
Most pages and the Angular Material docs use the Google Fonts API, which is however not GDPR compliant (IP is sent to Google).
We either have to download the fonts beforehand and include them statically which may result in outdated fonts and also reduces flexibility or use a nginx reverse proxy which which also doesn't seem to be the best idea (see [this thread](https://github.com/google/fonts/issues/1637)).
I would therefore recommend **not** to allow choosing a different font (I have never seen a website that allows to change a font).

### Migration
 - existing site settings in Config entity need to be migrated to own entity -> https://github.com/Aam-Digital/ndb-admin/pull/5
 - Existing default/`user_app` permissions need to be extended with `read` permissions for `SiteSettings` entity and manager permissions with `update`

2023-08-07 13:03 UTC, sleidig reviewed
nice work overall :-) 

Regarding style I notice that our accented buttons (primary action bottom right; Save buttons) now have black text/icons with, I think, a bit less contrast.

2023-08-07 19:46 UTC, TheSlimvReal commented on src/app/core/site-settings/site-settings.service.ts
> +      .catch(() => undefined);
There is a error happening on initial sync when the entity cannot yet be loaded but will be available through the local changes feed once it has been synced. The same approach can be found for the config and the permission entity. I wanted to merge this code as well.

2023-08-07 19:47 UTC, TheSlimvReal commented on src/app/core/site-settings/site-settings.ts
> +    "Aam Digital";
We still need to create the object at one point?

2023-08-08 06:47 UTC, sleidig commented on src/app/core/site-settings/site-settings.service.ts
> +      .catch(() => undefined);
maybe we can make this a bit more explicit + restrictive?

```suggestion
      .catch((err) => { /* ignore when unavailable during initial sync */ if(err.status !== 404) { throw err; } });
```

2023-08-08 06:48 UTC, sleidig commented on src/app/core/site-settings/site-settings.ts
> +    "Aam Digital";
hmm, true. Otherwise the form will run into issues

2023-08-22 13:00 UTC, TheSlimvReal commented on src/app/core/site-settings/site-settings.ts
> +  logoAsIcon = false;
Should we even offer this option?

2023-08-22 13:08 UTC, TheSlimvReal commented on src/app/core/site-settings/site-settings.service.ts
> +  icon = this.getPropertyObservable("icon").pipe(delay(0));
We could adopt Angular's naming convent to [suffix observables with `$`](https://angular.io/guide/rx-library#naming-conventions-for-observables).
However, we should then probably do this for all and generally I don't see a very big advantage of it (as typing already makes it obvious).

So I would like to keep this service in some way as it makes it very easy to handle everything related to the settings but if you have any suggestions in regards to naming etc. thats more then welcome.

2023-08-22 13:11 UTC, TheSlimvReal commented on src/styles/mdc_overwrites/mdb_overwrites.scss
This file holds the required overwrites for styles broken due to css variables (more background here https://github.com/angular/components/issues/25981#issuecomment-1515332869).

If we encounter any more issues we can add them here.

2023-08-22 13:13 UTC, TheSlimvReal commented on src/styles/mdc_overwrites/mdb_overwrites.scss
This file holds the required overwrites for styles broken due to css variables (more background here https://github.com/angular/components/issues/25981#issuecomment-1515332869).

If we encounter any more issues we can add them here.

2023-08-28 10:41 UTC, TheSlimvReal commented on src/app/core/language/language.module.ts
> +    enumService["cacheEnum"](availableLocales);
I have refactored the locales to be a `ConfigurableEnum`. 
This allows us to use the existing components for selecting but some things like adding new enum values don't really make sense and could lead to problems.
The alternative would be to have a new data type with explicit but not configurable values (just a enum).

2023-08-28 10:47 UTC, TheSlimvReal commented on src/styles/variables/_ndb-light-theme.scss
> +        contrast: map-get(mat.$orange-palette, contrast)
Contrast colors are not configurable and not adjusted based on the selected theme.

2023-09-04 07:28 UTC, TheSlimvReal commented
Should we also store the settings in the local storage in order to already apply them on startup?

2023-09-06 11:10 UTC, sleidig commented on src/app/core/site-settings/site-settings.service.ts
> +  icon = this.getPropertyObservable("icon").pipe(delay(0));
discussed and decided to leave as is.

While this duplicates properties between the service and SiteSettings entity class, this is a core service that will be much more used than changed, so it's worth prioritizing convenience for that.

2023-09-06 15:37 UTC, sleidig requested changes
the import module still has an orange background in some part. Otherwise looks and works great. Code also looks pretty good.

Great work, @TheSlimvReal ! :-)

2023-09-06 15:37 UTC, sleidig commented on src/app/core/site-settings/site-settings.service.ts
> +export class SiteSettingsService extends LatestEntity<SiteSettings> {
```suggestion
/**
 * Access to site settings stored in the database, like styling, site name and logo.
 */
@Injectable({
  providedIn: "root",
})
export class SiteSettingsService extends LatestEntity<SiteSettings> {
```

2023-09-06 15:56 UTC, TheSlimvReal commented on src/app/child-dev-project/notes/model/interaction-type.interface.ts
> -  color?: string;
Its already on the super class

2023-09-06 15:57 UTC, TheSlimvReal commented on src/app/core/analytics/analytics.service.spec.ts
> +  it("should set the site name as the organisation", () => {
Good point, we could just grep it from the `location.href` prop.

2023-09-06 15:57 UTC, TheSlimvReal commented on src/app/core/basic-datatypes/configurable-enum/configurable-enum-datatype/configurable-enum.datatype.spec.ts
> +  const TEST_CONFIG: InteractionType[] = [
The test uses the `isMeeting` property. Thats why it was needed.

2023-09-06 15:58 UTC, TheSlimvReal commented on src/app/core/config/config-fix.ts
> +    }
Isn't it a nice showcase for the white-label functionality?

2023-09-06 15:59 UTC, TheSlimvReal commented on src/app/core/entity/latest-entity.ts
> +export abstract class LatestEntity<T extends Entity> {
I like the `LatestEntityLoader` name. Would not want to call it service as it should really just serve as a incomplete helper feature than a standalone service.

2023-09-07 16:09 UTC, sleidig commented on src/app/core/config/config-fix.ts
> +    }
It is! But the demo already is pretty overwhelming, I think. So at least until we have a way to collapse things into a second level menu, I would hide it for now.

2023-09-08 11:23 UTC, sleidig approved these changes
tested, cleaned up and reviewed

2023-09-08 12:21 UTC, merged