added validator component
Aam-Digital/ndb-core pull request #2345
Opened 2024-04-17 04:57 UTC by Abhinegi2

closes: #XX

### Visible/Frontend Changes
- [x] 
- [ ] 

### Architectural/Backend Changes
- [x] 
- [ ]

2024-04-18 13:52 UTC, sleidig requested changes

2024-04-18 13:52 UTC, sleidig commented on src/app/core/admin/admin-entity-details/admin-entity-field/admin-entity-field.component.html
> +        [disabled]="false"
```suggestion
```

2024-04-18 13:52 UTC, sleidig commented on src/app/core/admin/admin-entity-details/admin-entity-field/admin-entity-field.component.html
>          label="Advanced Options & Validation [COMING SOON]"
```suggestion
        label="Advanced Options & Validation"
```

2024-04-18 13:52 UTC, sleidig commented on src/app/core/admin/admin-entity-details/admin-entity-field/configure-entity-field-validator/configure-entity-field-validator.component.scss
> +}
for a flex layout, you can use our global class "flex-column" without having to define your own css

2024-04-18 13:52 UTC, sleidig commented on src/app/core/admin/admin-entity-details/admin-entity-field/configure-entity-field-validator/configure-entity-field-validator.component.ts
> +    NgForOf,
I think ngFor is not used (anymore) in this component?

2024-04-18 13:52 UTC, sleidig commented on src/app/core/admin/admin-entity-details/admin-entity-field/configure-entity-field-validator/configure-entity-field-validator.component.ts
> +  fieldId: string;
not used? Can you go through the component and check whether all the inputs and properties are actually required for you final implementation?

2024-04-18 13:52 UTC, sleidig commented on src/app/core/admin/admin-entity-details/admin-entity-field/configure-entity-field-validator/configure-entity-field-validator.component.html
> +    <mat-checkbox i18n formControlName="required"> Is Required? </mat-checkbox>
these checkboxes do not display as a new line yet:
![image](https://github.com/Aam-Digital/ndb-core/assets/1682541/b6e2a05b-0df9-4582-b204-aa96d6649811)

maybe needs to be wrapped in a form-field or div or something?

2024-04-18 13:52 UTC, sleidig commented on src/app/core/admin/admin-entity-details/admin-entity-field/configure-entity-field-validator/configure-entity-field-validator.component.html
> +    </mat-form-field>
hide if entityField dataType is not "number"

2024-04-18 13:52 UTC, sleidig commented on src/app/core/admin/admin-entity-details/admin-entity-field/configure-entity-field-validator/configure-entity-field-validator.component.html
> +    </mat-form-field>
hide regex and "valid email" if datatype is not "string"

2024-04-18 18:38 UTC, Abhinegi2 commented
@sleidig did requested changes can you please check now?

2024-04-23 09:22 UTC, sleidig commented on src/app/core/admin/admin-entity-details/admin-entity-field/configure-entity-field-validator/configure-entity-field-validator.component.html
> +  <mat-tab-group formGroupName="validatorForm">
my IDE remarks that mat-tab-group is not allowed here (must be within the template that has the mat-tab --> take out of the template here and wrap in admin-entity-field instead)

2024-04-23 11:22 UTC, Abhinegi2 commented
@sleidig did the requested changes, please have a look now.

2024-04-23 12:36 UTC, sleidig approved these changes

2024-04-23 13:22 UTC, sleidig commented on src/app/core/admin/admin-entity-details/admin-entity-field/configure-entity-field-validator/configure-entity-field-validator.component.spec.ts
> +fdescribe("ConfigureEntityFieldValidatorComponent", () => {
```suggestion
describe("ConfigureEntityFieldValidatorComponent", () => {
```

2024-04-23 14:12 UTC, merged