feat: support for inheritance default field values
Aam-Digital/ndb-core pull request #2362
Opened 2024-04-24 16:07 UTC by tomwwinter

related: #2217

### Visible/Frontend Changes
- [ ] When creating/editing an entity, configured inheritance default values are set

### Architectural/Backend Changes
- [ ] created separated service for default-field-values
- [ ] created use case for default-field-values logic

2024-04-25 08:49 UTC, sleidig requested changes
Really nice, clean code :heart_eyes:   Thanks for adding JsDoc also.

Functional testing:
- [x] static default value should be applied on new record
- [x] dynamic default value ($now, $current_user) should be applied on new record
- [ ] dynamic default value should not overwrite existing value :warning: 
- [x] static default value should not overwrite (explicitly cleared) empty field on existing entity :warning: 
- [x] inherited default value should be applied whenever the related reference is changed (on new/existing entity)
- [ ] inherited value can be overwritten manually :warning: (currently resets to inherited upon save)

maybe we can add some of these edge cases to the unit tests, also? (-> TDD)

2024-04-25 09:05 UTC, tomwwinter commented on src/app/core/entity/default-field-value.service.spec.ts
> +  it("should apply inheritance modes before static and dynamic modes", () => {
The Inheritance mode listen to changes and loads the entities then. When static value is processed, before the inheritance hook is registered, the loading does not trigger.

2024-04-25 09:06 UTC, tomwwinter commented on src/app/core/entity/default-field-value/handle-default-field-values.usecase.spec.ts
> +    "reverence-1": new FormControl(),
yes 🙈

2024-04-29 10:26 UTC, tomwwinter commented on src/app/core/entity/default-field-value/handle-default-field-values.usecase.ts
> +      }
We need to separate the "isNew" and the "editing" case here, when creating new, we want to overwrite the value, if empty and not dirty.

when we edit a field, we don't want to overwrite a value, even when it is untouched. Right?

2024-04-30 07:25 UTC, sleidig reviewed
Functional testing:
| | static | dynamic | inherited |
| -------- | -------- | ------- | ------- |
| correct default value applied on new record                               | x | x | x (upon selecting ref) |
| can overwrite manually while creating new                                 | x | x | x |
| can delete/clear manually while creating new                             | x | x | x |
| keeps overwritten value when opening / editing existing             | x | x | x |
| keeps empty overwritten value when opening / editing existing  | x | x | x |

inherited value functionalities:
- [x] sets inherited values upon selecting the reference (new entity)
- [x] updates inherited values upon changing reference
- [x] clears inherited values upon removing reference
- [x] keeps manually set values, not overwriting them even when reference changes
- [ ] applies inherited values also when editing an existing entity, when the user changes the reference/parent

I think the last point is a rather common use case: A user creates an incomplete record, then goes back to edit and select a "parent" reference. This case should trigger the same logic editing an existing record as for editing a new record.
(This is a technical challenge of course, because it's difficult to detect if a field has been manually set/cleared before the last save, as we can't rely on form field dirty state ...)

Apart from this (important) edge case, seems to work great now! :+1:

2024-04-30 13:27 UTC, sleidig approved these changes

2024-05-03 12:04 UTC, tomwwinter commented on src/app/core/entity/schema/entity-schema-field.ts
>    defaultValue?: PLACEHOLDERS | any;
I added the migrations and removed the deprecated code. But the latest changes may conflict with the changes from the array-refactoring. Maybe just merge this first: https://github.com/Aam-Digital/ndb-core/pull/2369

2024-05-03 13:08 UTC, sleidig commented on src/app/core/config/config.service.ts
> +    (value) => value == configPart,
do we stick to JavaScript conventions of always using `===` comparison?

2024-05-21 09:06 UTC, merged