Url datatype
Aam-Digital/ndb-core pull request #2646
Opened 2024-10-30 15:39 UTC by sadaf895

closes: #2460

2024-10-31 08:47 UTC, sleidig requested changes
It seems like you didn't test this in the app yet :wink:   It didn't work for me because we forgot to register the components (see my commit now).

The component still has some issues. Test it while keeping the Developer Console open and see various errors. I think it is not "allowed" to mark a `<a` with matInput, this only works for `<input` as far as I know.

2024-10-31 08:47 UTC, sleidig commented on src/app/core/basic-datatypes/string/display-url/display-url.component.ts
> +    <span *ngIf="!value">No URL available</span>
```suggestion
    <span *ngIf="!value">-</span>
```

2024-10-31 08:47 UTC, sleidig commented on src/app/core/basic-datatypes/string/edit-url/edit-url.component.html
> +    <span *ngIf="formControl.errors?.['pattern']">Invalid URL format</span>
```suggestion
    <span *ngIf="formControl.errors?.['pattern']" i18n>Invalid URL format</span>
```
marking this to be translatable

2025-02-07 09:23 UTC, sleidig commented
`EditFileComponent` might have some logic applied that allows users to click even on the disabled field. Maybe you, @Abhinegi2 and @sadaf895, can look at this together to finish this PR

2025-02-07 11:53 UTC, Abhinegi2 commented
@sadaf895 I made some modifications to allow user clicks even when the form is disabled. I also added test cases and updated the cursor styling. Please review these changes and let me know if any functionality is missing.  

To enable user clicks while the form is disabled, I followed this approach(which we already following in `EditFileComponent ` ):  
[(https://stackoverflow.com/questions/3100319/event-on-a-disabled-input/32925830#32925830)](https://stackoverflow.com/questions/3100319/event-on-a-disabled-input/32925830#32925830)

2025-02-10 14:07 UTC, sleidig requested changes
Code and functionality looks pretty good already :slightly_smiling_face: 

From functional testing a few suggestions to polish this further. Can you take these points up again, @sadaf895 ?

- [x] in the list view, the link is not working and instead the details view of record is loaded. If clicking exactly on that link, I would like to instead open the external url in a new tab (@Abhinegi2 has implemented something similar only last week)
- [x] The form field's link text should look a bit more like a clickable link. I suggest we give this an underline styling or maybe underline on hover (i.e. maybe giving this our global "clickable" css class)
- [x] if the value is not a valid url (e.g. just some random text), this anyway opens a new tab to our app. In such a case the link should not be clickable (and not styled like a link
- [ ] if I put a URL without leading http or https it is not opened as an external link. Probably we should prefix that automatically if it is required to work as links. Maybe we can use a similar design to the screenshot below, where "https://" is always automatically prefixed and cannot be changed?

![image](https://github.com/user-attachments/assets/e84a427b-80e8-48fd-a21b-5c0c08e45a80)

If unsure about design, do ask for feedback on our Slack

2025-02-10 14:07 UTC, sleidig commented on src/app/core/basic-datatypes/string/edit-url/edit-url.component.html
> +    placeholder="Enter URL"
```suggestion
    placeholder="Enter URL"
    i18n-placeholder
```

2025-02-10 14:07 UTC, sleidig commented on src/app/core/basic-datatypes/string/edit-url/edit-url.component.html
> +    <span *ngIf="formControl.errors?.['pattern']">Invalid URL format</span>
this i18 tag is still missing.

Also, is "pattern" used anywhere to check validity?

2025-02-11 14:57 UTC, sleidig commented on src/app/core/basic-datatypes/string/edit-url/edit-url.component.ts
> +  isValidUrl(value: string | null): boolean {
unit test cases to implement for this functionality:
- `it("should be invalid for value that is not a complete URL"`:  input value: `"example"`, expected result: `false`
- `it("should be valid for empty value"`:  input value: `""` or input value: `null` (test both), expected result: `true`
- `it("should be valid for url-like value"`:  input value: `"https://example.com"`, expected result: `true`

2025-02-12 09:24 UTC, sadaf895 commented
@george-neha Can you please check the functionality as a user's perspective and share your feedback on it.

2025-02-12 12:46 UTC, sadaf895 commented
> As a user, I will do either of the two things:
> 
> 1. type out the website link (more probable),
> 2. copy and paste the link the URL.
> 
> I feel adding a prefix to the website field with https:// and letting the user type in the website name would be more user-friendly. (see image below) <img alt="image" width="213" src="https://private-user-images.githubusercontent.com/189214052/412364658-ec0fe781-cde3-4297-bb1e-c4251a4e4290.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzkzNjQ1NTIsIm5iZiI6MTczOTM2NDI1MiwicGF0aCI6Ii8xODkyMTQwNTIvNDEyMzY0NjU4LWVjMGZlNzgxLWNkZTMtNDI5Ny1iYjFlLWM0MjUxYTRlNDI5MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDIxMlQxMjQ0MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NjJkZjBkY2MyYjBmYjRkYWY4OTI1YzE1YmM2NGU1NzI2ZGNjZGI5OWZiYjNjOTRmOWFjYmVhOWM5MmJmMDY3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.XFyAbkl1p_Ib8i-wGoMTRgmEH5p423vinjZ1zwgrlLI">
> 
> In scenarios where a user will copy-paste the URL. Would it be possible to truncate the additional https://? What do you think @sadaf895

@george-neha Can you now check the functionality? Any improvement or modification is needed?
@sleidig @Abhinegi2 Can you both also please check the updated functionality or any feedback you want to give regarding this?

2025-02-13 06:20 UTC, Abhinegi2 commented
@sadaf895 While testing, I found a UI glitch. Here’s how to reproduce it:

- Enter or paste any website URL in the field (e.g., https://www.talisman.org/tao/).
- Try deleting the URL one character at a time. The `https://` prefix doesn’t get removed and keeps reappearing in a loop. 

However, if you select(complete url) and delete the entire url at once, it works correctly.

2025-02-14 12:46 UTC, Abhinegi2 commented
@george-neha could you test it again, and let me know if you have any suggestions

2025-02-17 18:05 UTC, sleidig commented
This is not properly usable yet, unfortunately ...
Adding and deleting parts of the prefix creates a number of weird results and issues.

I think we should maybe spell out sensible behavior and test cases for these edge cases of editing:
- trying to delete part of the prefix as a user
- supporting something other than https (just http, for example)


-----
Clicking links seems to work very well now, however :+1: 

Only the cursor here should be a pointer to indicate clickability:
![image](https://github.com/user-attachments/assets/93bb0681-b52d-4394-b6bb-8cc823b51f95)

2025-02-18 10:22 UTC, sadaf895 commented
Test Cases for Editing a Website URL:

[ ] Entering a valid URL
- Input: http://example.com
- Expected Output: URL is saved and displayed as a clickable link.

[ ] Editing an existing URL
- Given: http://old-site.com
- Action: Change to http://new-site.com and save.
- Expected Output: New URL is displayed and clickable.

[ ] Clearing an existing URL
- Given: http://example.com
- Action: Remove the URL and save.
-Expected Output: The field is empty after saving.

2025-02-21 13:17 UTC, sadaf895 commented
list of issues need to be fixed
- [ ] for any changes made it need to click the save button twice
- [ ]  if I delete any character/letter of "https://," then the system is auto-creating the precursor of http:// resulting in a website link http://https:/snuniv.in
- [ ] invalid URL ka functionality is now working only after i click on save and click on edit again.

2025-02-21 14:36 UTC, sleidig commented
After discussing the problems giving users confusing results when changing the prefix, we decided the following should be the behaviour:

- _typing / pasting something: if without "http://" or "https://" prefix -> immediately add "https://" automatically_
  - if the first entered letter is "x" (for example) -> show "https://x"
  - if the first entered letter is "h" -> show "https://" (not "https://h")
  - if the first letter is a whitespace " " -> trim that and show "https://"
  - if the value (pasted) is a url starting with "http://" -> do not add a prefix and keep the value as it is
  - if the value (pasted) is a url starting with "https://" -> do not add a prefix and keep the value as it is
- _changing an existing value: do not "accept" changes that "break" the valid prefix_
  - changing any part after the "://" -> just do the change without changes (trim whitespaces at the end)
  - deleting any letter of the "https://" (e.g. new value "htps://google.com") -> revert back to the valid "https://" (e.g. "https://google.com")
  - changing from "https://" to "http://" (e.g. new value "http://google.com") -> accept new value (e.g. "http://google.com")
  - adding/changing any letter to the prefix: e.g. "httpx://google.com" -> "https://google.com"
  - "httpS://" -> "https://" (but not important because URLs are case insensitive)

2025-02-24 15:17 UTC, sleidig commented
@sadaf895 , can you still check about the cursor pointer style (see comment above)? In EditFile field the cursor does change, for example.

Otherwise this is good to go, I think :-)

2025-02-27 10:52 UTC, sleidig approved these changes
Seems to work well now and looks like clean code :100: 

Nice work, @sadaf895 . This certainly was more complex than expected and took a long time. But the new dataType will be a really good feature for users, giving much better UX there.
Thanks for your support here, @george-neha , @Abhinegi2

2025-02-27 11:04 UTC, merged