[Feat]: Notification Setting Page
Aam-Digital/ndb-core pull request #2712
Opened 2024-12-12 08:43 UTC by Ayush8923

closes: #XX

### Visible/Frontend Changes

- [x]
- [ ]

2024-12-17 06:20 UTC, Ayush8923 commented
> Deployed to https://pr-2712.aam-digital.net/

@george-neha Please test the notification setting page UI inside the profile page in the above-mentioned URL and share your feedback/suggestions. For reference: please check this issue's [comments](https://github.com/Aam-Digital/ndb-core/issues/2696#issuecomment-2531195353).

2024-12-17 07:29 UTC, Ayush8923 commented on src/app/core/entity/entity-type-select/entity-type-select.component.html
> +<mat-form-field>
As per the discussion on Slack, for now we can use `mat-form-field` inside the EntityTypeSelectComponent. As for the approach of splitting `mat-form-field` from the component would require us to implement extends `CustomFormControlDirective` on the `EntityTypeSelectComponent`. For this, we can create the issue for that and implement it later.

2024-12-17 13:48 UTC, george-neha commented
UI working as per functionality. 
**Suggestion:** The Save button should be enabled only if any changes are made to the notification settings. 
<img width="960" alt="image" src="https://github.com/user-attachments/assets/896bb9b1-c15e-43be-8d88-2412246fe23a" />

2024-12-17 16:04 UTC, Ayush8923 commented
> UI working as per functionality. **Suggestion:** The Save button should be enabled only if any changes are made to the notification settings. <img alt="image" width="960" src="https://private-user-images.githubusercontent.com/189214052/396519764-896bb9b1-c15e-43be-8d88-2412246fe23a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ0NTE2MjgsIm5iZiI6MTczNDQ1MTMyOCwicGF0aCI6Ii8xODkyMTQwNTIvMzk2NTE5NzY0LTg5NmJiOWIxLWMxNWUtNDNiZS04ZDg4LTI0MTIyNDZmZTIzYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxN1QxNjAyMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MGQ0MGY1MWJmOTJlZTVjNDc0NjBiY2IwN2E2NTk2OGU0ZWQxNWFmMWU1YzYzZGZiMGFmZmVjNWRkOWIzMzE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.isA1v8PyFHixs-S350wzhEBFR9oMx76-NuugE8gfu8Y">

Thanks for this suggestion @george-neha.
Yes, we will implement this logic in this [issue](https://github.com/Aam-Digital/ndb-core/issues/2723) and also, and I have also added this suggestion in this issue description.

2024-12-24 16:08 UTC, Ayush8923 commented
> Deployed to https://pr-2712.aam-digital.net/

@george-neha As discussed regarding the [notification settings page UI](https://github.com/Aam-Digital/ndb-core/issues/2696#issuecomment-2553402972), I have updated the UI accordingly. You can test the changes using the link [provided above](https://github.com/Aam-Digital/ndb-core/pull/2712#issuecomment-2538211090). Please let me know if any further adjustments are needed or if you have any suggestions.

2024-12-27 15:24 UTC, sleidig reviewed
UI looks good to me mostly (no code review yet, as we have to resolve merge conflicts since the base branch was merged and squashed recently).

- [ ] I think we should more prominently highlight if push notifications are disabled. Maybe show a banner in the "Where you receive notifications" or a warning icon next to the "Push Notification" entry if it is not enabled?
- [x] "Notification Method" dropdown should be enabled and allow multi-select of all option - even if that is only "Push Notification" currently and nothing else is supported. That will make the purpose clearer to the user. (and they can actually disable "push" and just see it in the "Notification Center", if they want)
- [x] The initial rule cannot be deleted. I would rather display an empty section with only the "add new" button in that case.

2024-12-30 14:06 UTC, george-neha commented
> * [ ]  I think we should more prominently highlight if push notifications are disabled. Maybe show a banner in the "Where you receive notifications" or a warning icon next to the "Push Notification" entry if it is not enabled?

@sleidig @Ayush8923 for this I had initially suggested an approach where the user will first notice "where you receive notifications" before they take action on individual notifications here under this [issue](https://github.com/Aam-Digital/ndb-core/issues/2696#issuecomment-2559685167)

> 1.The "where you receive notifications" section should be moved up. In situations where multiple notification conditions are added, selecting where the notifications should be received requires scrolling down to enable or disable them. 

I honestly feel the page can get a hierarchy refresh which would benefit the user from not missing crucial information. 

Secondly, for additional highlight we can use status badges using text "Enabled/ Disabled" next to the toggle button. 

Here is an example I saw from Material Design:

<img width="960" alt="image" src="https://github.com/user-attachments/assets/92cda08c-b4f0-4a2c-8202-7a854be8aa95" />

The banner may not scale in the future if we need to highlight about email notifications too. 

What do you think?

2024-12-30 14:14 UTC, sleidig commented
I somewhat disagree about changing the order, moving "where  you receive notifications" to the top: While it is important for users to understand if "push" is not enabled, I expect this setting to hardly ever be changed while users may regularly change the individual notification rules. Therefore, I believe that section is much more likely to be relevant and should stay on top.

2025-01-02 07:39 UTC, Ayush8923 commented
> I think we should more prominently highlight if push notifications are disabled. Maybe show a banner in the "Where you receive notifications" or a warning icon next to the "Push Notification" entry if it is not enabled?

@sleidig @george-neha I have added a warning icon next to the "Where you receive notifications" section title if the user's notifications are not enabled. Can you please check it once and let me know if any changes or updates are needed in the Notification Settings page UI?
<img width="1495" alt="image" src="https://github.com/user-attachments/assets/f007bf14-457b-44e0-a967-4de5ff1e4c5e" />

2.  As per the @george-neha suggestion, the UI is looking like this, please check this also and please share your suggestion/thoughts. 
<img width="1506" alt="image" src="https://github.com/user-attachments/assets/61faeb8c-76ad-40b1-afa7-f2c7ab6d1623" />

2025-01-02 08:24 UTC, sleidig commented
> > I think we should more prominently highlight if push notifications are disabled. Maybe show a banner in the "Where you receive notifications" or a warning icon next to the "Push Notification" entry if it is not enabled?
> 
> @sleidig @george-neha I have added a warning icon next to the "Where you receive notifications" section title if the user's notifications are not enabled. Can you please check it once and let me know if any changes or updates are needed in the Notification Settings page UI?
> <img width="1495" alt="image" src="https://github.com/user-attachments/assets/f007bf14-457b-44e0-a967-4de5ff1e4c5e" />
> 
> 2.  As per the @george-neha suggestion, the UI is looking like this, please check this also and please share your suggestion/thoughts. 
> <img width="1506" alt="image" src="https://github.com/user-attachments/assets/61faeb8c-76ad-40b1-afa7-f2c7ab6d1623" />
> 
> 

I like it. If we have the enabled badge there, maybe turn the warning icon into a red "disabled " badge for consistency and better visibility?

2025-01-02 09:57 UTC, Ayush8923 commented
> I like it. If we have the enabled badge there, maybe turn the warning icon into a red "disabled " badge for consistency and better visibility?

Thanks for this suggestion, I have updated the UI according. So if the push notification is enabled then the `Enabled` badge is showing next to the `Where you receive notifications` section and if the push notification is disabled then the `Disabled` badge is showing.

2025-01-02 10:06 UTC, Ayush8923 commented
> Deployed to https://pr-2712.aam-digital.net/

@george-neha I'm Moving this to Functional Review. You can test the changes using the link [provided link above](https://github.com/Aam-Digital/ndb-core/pull/2712#issuecomment-2538211090). Please let me know if any further adjustments are needed or if you have any suggestions.

2025-01-03 08:27 UTC, sleidig requested changes
Some last glitches, otherwise both code and UI look good :+1:

2025-01-03 08:27 UTC, sleidig commented on src/app/features/notification/notification-settings/notification-settings.component.scss
> +}
Why is this sometimes 30px sometimes 32px? We should probably work with our standard sizes from `@use "variables/sizes";`

2025-01-03 08:27 UTC, sleidig commented on src/app/features/notification/notification-settings/notification-settings.component.scss
> +  box-shadow: 0px 0px 10px 0px rgba(0, 0, 0, 0.1);
use mat-elevation for consistency?
`@use "@angular/material/core/style/elevation" as mat-elevation;`

2025-01-03 11:56 UTC, Ayush8923 commented on src/app/core/entity/entity-type-select/entity-type-select.component.ts
> +// TODO: Need to use the CustomFormControlDirective abstract class instead of ControlValueAccessor.
@sleidig The reason for making changes in this component was that earlier we were splitting the `mat-form-field`. We have an existing component for the entity field but we couldn't import the `EntitySelectComponent`, which is a dynamic component, into an HTML file. As a result, we were encountering an error like `No provider for NgControl found in NodeInjector.` Based on previous discussions, we realized that extending the `CustomFormControlDirective` is necessary, as this is the long-term solution to implement special components as form controls. However, for now, the approach might be too complex and time-consuming. So that's why we did not extend the `CustomFormControlDirective`. Here is the discussion [link](https://aam-digital.slack.com/archives/D080VLA5WUB/p1734366972998179?thread_ts=1734366484.204119&cid=D080VLA5WUB).

Additionally, in this component, the test cases were failing, so to resolve the issues with the test cases, I added the required functions.

2025-01-03 13:33 UTC, Ayush8923 commented on src/app/features/notification/notification-settings/notification-settings.component.scss
> +}
Yes, I added the breakpoint because, in the `notification-panel-wrapper`, we have two sections: one for the notification rule input field and another for the notification rule action items. On large screens (1400px, I updated the breakpoint to fix the UI breaking issue you mentioned), we need all the action items and input fields in a single row. For screens smaller than 1400px, we can display the notification rules in a column layout. However, if I remove the breakpoints and use `flex-wrap`, the entire UI breaks because each input field has its own defined width.

2025-01-03 13:36 UTC, Ayush8923 commented on src/app/features/notification/notification-settings/notification-settings.component.scss
> +}
Thanks, I update this code according to your suggestion.

2025-01-03 15:01 UTC, sleidig approved these changes
Looks good :slightly_smiling_face:

2025-01-03 16:06 UTC, merged