Components and Filter for ConfigurableEnum values
Aam-Digital/ndb-core pull request #599
Opened 2021-01-11 22:50 UTC by sleidig

required for adaptions for new customers

### Architectural/Backend Changes
- [x] add a filter type `"configurable-enum"` (see `ConfigurableEnumFilterConfig`) to display filter options in lists based on an enum in the config
- [x] refactor entity-list to extract filter component template
- [x] add field types for form (`input === 'configurable-enum-select'"`) and list (`DisplayConfigurableEnumComponent`) to display ConfigurableEnumValues

2021-01-11 22:52 UTC, sleidig commented on src/app/child-dev-project/attendance/attendance-analysis/attendance-analysis.component.ts
> +      // filteredData = filteredData.filter(f.getSelectedFilterFunction());
this component will be completely replace due to the event attendance changes. therefore no fixes here

2021-01-13 12:08 UTC, TheSlimvReal commented on src/app/core/entity-components/entity-list/entity-list.component.ts
> +        return filter.options;
I think I made a mistake concerning the return type here. The other options only return `null`

2021-01-13 12:15 UTC, TheSlimvReal approved these changes
Very nice change, cleaned up a lot of things. I just found a little type issue (that I implemented myself earlier). please have a look at the changes that I added.

2021-01-13 12:46 UTC, TheSlimvReal requested changes
Just some styling issues

2021-01-13 12:46 UTC, TheSlimvReal commented on src/app/core/entity-components/entity-list/list-filter/list-filter.component.html
> +<div *ngIf="displayAsToggle">
The styling is not very good yet

![filters_screenshot](https://user-images.githubusercontent.com/33730997/104454124-a91ac200-55a5-11eb-87d1-f12738def17a.png)

2021-01-13 15:04 UTC, TheSlimvReal approved these changes
Looks all fine. Good work!

2021-01-13 15:10 UTC, merged