Dashboard shortcut widget
Aam-Digital/ndb-core pull request #739
Opened 2021-04-06 09:02 UTC by sleidig

~see issue~

### Visible/Frontend Changes
- [x] New dashboard widget: `"DashboardShortcutWidget"` available, showing simple table of shortcuts for easier navigation 

### Architectural/Backend Changes
- [x] some basic refactorings (see commits)

_Merge without squashing to keep the refactoring commits in the git history_

2021-04-06 17:28 UTC, TheSlimvReal requested changes
Looks fine, just a small typo. 
However, the styling of other widgets got(?) broken.
![widget-shortcut](https://user-images.githubusercontent.com/33730997/113753212-228e0080-970e-11eb-8cf9-5c878195b3c1.png)
Also I am wondering who exactly is targeted by this widget? Phone users?

2021-04-06 17:28 UTC, TheSlimvReal commented on src/app/core/dashboard-shortcut-widget/dashboard-shortcut-widget/dashboard-shortcut-widget.component.ts
> +  /** entries representing each representing one line displayed as a shortcut */
```suggestion
  /** entries, each representing one line displayed as a shortcut */
```

2021-04-07 06:37 UTC, sleidig commented on src/app/core/dashboard-shortcut-widget/dashboard-shortcut-widget/dashboard-shortcut-widget.component.ts
> +  /** entries representing each representing one line displayed as a shortcut */
:+1:

2021-04-07 06:44 UTC, sleidig commented
Thanks for pointing out the styling issue - somehow I missed the BMI dashboard.

The feature is intended especially for mobile users but also for more specific quick actions on desktop, like directly navigation to the form to create a new child

2021-04-07 06:54 UTC, merged