Add children from school
Aam-Digital/ndb-core pull request #944
Opened 2021-08-09 16:36 UTC by kirtijadhav

see issue: #XX

### Visible/Frontend Changes
- [ ] 
- [ ] 

### Architectural/Backend Changes
- [x] add child new button
- [ ]

2021-08-11 12:17 UTC, TheSlimvReal requested changes

2021-08-11 12:17 UTC, TheSlimvReal commented on src/app/child-dev-project/children/model/childSchoolRelation.ts
> +    label: $localize`:Label for the child of a relation:Child`,
A german translation has to be provided for this

2021-08-11 12:17 UTC, TheSlimvReal commented on src/app/child-dev-project/schools/children-overview/children-overview.component.html
> +  ></mat-icon>
The styling of the '+' button is a little off

![add_child_button](https://user-images.githubusercontent.com/33730997/129026514-9cecefd0-7c40-4690-a426-949cffe3e104.png)

2021-08-11 12:17 UTC, TheSlimvReal commented on src/app/child-dev-project/schools/children-overview/children-overview.component.ts
> +    console.log('addChildClick')
remove this line

2021-08-11 12:17 UTC, TheSlimvReal commented on src/app/child-dev-project/children/model/childSchoolRelation.ts
> +    label: $localize`:Label for the child of a relation:Child`,
See our guide for [building localizable components](https://aam-digital.github.io/ndb-core/documentation/additional-documentation/how-to-guides/build-localizable-components.html)

2021-08-19 07:21 UTC, TheSlimvReal requested changes
Looks very good but there are some problems:

- [ ] Since autocomplete was added, the children are not added to the list any more
- [ ] The label is very specific to the children case, we should find a way to make if configurable

2021-08-23 07:42 UTC, TheSlimvReal requested changes
I guess there was a small misunderstanding. The important part is that just the ID and not the whole entity is assigned as value.

2021-08-23 07:42 UTC, TheSlimvReal commented on src/app/core/entity-components/entity-utils/dynamic-form-components/edit-single-entity/edit-single-entity.component.html
> +    <mat-option *ngFor="let getId of filteredChildren | async" [value]="getId">
```suggestion
    <mat-option *ngFor="let child of filteredChildren | async" [value]="child.getId()">
```

2021-08-23 07:42 UTC, TheSlimvReal commented on src/app/core/entity-components/entity-utils/dynamic-form-components/edit-single-entity/edit-single-entity.component.html
> +        [entityToDisplay]="getId"
```suggestion
        [entityToDisplay]="child"
```

2021-08-24 09:43 UTC, TheSlimvReal commented
The functionality works well now.
The problem is however, that the ID of the child is shown in the input field rather then the name. This should be changed.

2021-08-31 19:10 UTC, TheSlimvReal approved these changes
Good job, works well now

2021-08-31 19:11 UTC, merged

2021-09-13 07:25 UTC, sleidig commented
closes #758